sudo: false
language: node_js
before_install:
  - npm install -g npm@latest
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '14'
script:
  - npm start validate
after_success:
  - npx codecov
branches:
  only:
    - master
